filter:
  excluded_paths:
    - 'tests/*'
    - '*.tpl.php'
checks:
  php: true
coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
      other:
        after_type_cast: false
build:
  tests:
    override:
      -
        command: 'phpunit --configuration=phpunit.xml --coverage-clover=phpunit-coverage.xml'
        coverage:
          file: 'phpunit-coverage.xml'
          format: 'php-clover'
