filter:
  excluded_paths:
    - 'tests/*'
    - '*.tpl.php'
checks:
  php: true
coding_style:
  php:
    spaces:
      around_operators:
        concatenation: true
      other:
        after_type_cast: false
