<?php

use Asymptix\web\Request;
use Asymptix\web\Http;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-09-28 at 18:37:03.
 */
class RequestTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Request
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $_REQUEST['var'] = "REQUEST var";
        $_GET['var'] = "GET var";
        $_POST['var'] = "POST var";

        $_REQUEST['complex']['var']['value'] = 123;
        $_GET['complex']['var']['value'] = "abc";
        $_POST['complex']['var']['value'] = "qwerty";

        $this->object = new Request;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {}

    /**
     * @covers \Asymptix\web\Request::isFormSubmitted
     * @todo   Implement testIsFormSubmitted().
     */
    public function testIsFormSubmitted() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    public function testGetFieldValue_request() {
        $this->assertEquals(
                $_REQUEST['var'],
                Request::getFieldValue('var')
        );
    }

    public function testGetFieldValue_get() {
        $this->assertEquals(
                $_GET['var'],
                Request::getFieldValue('var', Http::GET)
        );
    }

    public function testGetFieldValue_post() {
        $this->assertEquals(
                $_POST['var'],
                Request::getFieldValue('var', Http::POST)
        );
    }

    public function testGetFieldValue_complex() {
        $this->assertEquals(
                123,
                Request::getFieldValue('complex[var][value]')
        );
    }

    public function testGetFieldValue_complex_get() {
        $this->assertEquals(
                "abc",
                Request::getFieldValue('complex[var][value]', Http::GET)
        );
    }

    public function testGetFieldValue_complex_post() {
        $this->assertEquals(
                "qwerty",
                Request::getFieldValue('complex[var][value]', Http::POST)
        );
    }

    public function testGetFieldValue_notExists() {
        $this->assertNull(Request::getFieldValue('name'));
    }

    public function testGetFieldValue_complex_notExists() {
        $this->assertNull(Request::getFieldValue('name[test][var]'));
    }

    /**
     * @covers \Asymptix\web\Request::setFieldValue
     * @todo   Implement testSetFieldValue().
     */
    public function testSetFieldValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\web\Request::rememberField
     * @todo   Implement testRememberField().
     */
    public function testRememberField() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\web\Request::forgotField
     * @todo   Implement testForgotField().
     */
    public function testForgotField() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\web\Request::forgotFields
     * @todo   Implement testForgotFields().
     */
    public function testForgotFields() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\web\Request::changeFieldValue
     * @todo   Implement testChangeFieldValue().
     */
    public function testChangeFieldValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\web\Request::castFieldValue
     * @todo   Implement testCastFieldValue().
     */
    public function testCastFieldValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\web\Request::normalizeCheckboxes
     * @todo   Implement testNormalizeCheckboxes().
     */
    public function testNormalizeCheckboxes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\web\Request::removeFields
     * @todo   Implement testRemoveFields().
     */
    public function testRemoveFields() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
