<?php

use Asymptix\core\Tools;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-08-03 at 19:26:54.
 */
class ToolsTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Tools
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Tools();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \Asymptix\core\Tools::isFormSubmitted
     *
     * @todo   Implement testIsFormSubmitted().
     */
    public function testIsFormSubmitted()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\core\Tools::getFieldValue
     *
     * @todo   Implement testGetFieldValue().
     */
    public function testGetFieldValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\core\Tools::setFieldValue
     *
     * @todo   Implement testSetFieldValue().
     */
    public function testSetFieldValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\core\Tools::isFilterExists
     *
     * @todo   Implement testIsFilterExists().
     */
    public function testIsFilterExists()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\core\Tools::getFilterValue
     *
     * @todo   Implement testGetFilterValue().
     */
    public function testGetFilterValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\core\Tools::rememberField
     *
     * @todo   Implement testRememberField().
     */
    public function testRememberField()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\core\Tools::forgotField
     *
     * @todo   Implement testForgotField().
     */
    public function testForgotField()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\core\Tools::forgotFields
     *
     * @todo   Implement testForgotFields().
     */
    public function testForgotFields()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\core\Tools::changeFieldValue
     *
     * @todo   Implement testChangeFieldValue().
     */
    public function testChangeFieldValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\core\Tools::castFieldValue
     *
     * @todo   Implement testCastFieldValue().
     */
    public function testCastFieldValue()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\core\Tools::normalizeCheckboxes
     *
     * @todo   Implement testNormalizeCheckboxes().
     */
    public function testNormalizeCheckboxes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\core\Tools::removeFields
     *
     * @todo   Implement testRemoveFields().
     */
    public function testRemoveFields()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\core\Tools::isInteger
     *
     * @todo   Implement testIsInteger().
     */
    public function testIsInteger()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\core\Tools::isDouble
     *
     * @todo   Implement testIsDouble().
     */
    public function testIsDouble()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\core\Tools::isDoubleString
     *
     * @todo   Implement testIsDoubleString().
     */
    public function testIsDoubleString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\core\Tools::toDouble
     *
     * @todo   Implement testToDouble().
     */
    public function testToDouble()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\core\Tools::isNumeric
     *
     * @todo   Implement testIsNumeric().
     */
    public function testIsNumeric()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\core\Tools::isBoolean
     *
     * @todo   Implement testIsBoolean().
     */
    public function testIsBoolean()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\core\Tools::isString
     *
     * @todo   Implement testIsString().
     */
    public function testIsString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\core\Tools::isObject
     *
     * @todo   Implement testIsObject().
     */
    public function testIsObject()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Asymptix\core\Tools::isInstanceOf
     *
     * @todo   Implement testIsInstanceOf().
     */
    public function testIsInstanceOf()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }
}
